# BASE UI
ColorColumn: "- backgroundDark"
Conceal: ""
Cursor: "- color3"
CursorIM: ""
CursorColumn: "- backgroundDark"
CursorLine: "- backgroundDark"
CursorLineNr: "color15 backgroundDark"
LineNr: "color7 background"
Directory: ""
DiffAdd: "color10 background"
DiffChange: "color6 background u"
DiffDelete: "color1 background"
DiffText: "foreground"
ErrorMsg: "color1"
VertSplit: "color8 background"
Folded: "color7 color0"
FoldColumn: ""
SignColumn: "color15 background"
IncSearch: "background color11"
MatchParen: "background color14"
ModeMsg: ""
MoreMsg: ""
NonText: "color8"
Normal: "foreground background"
PMenu: "foreground color0"
PMenuSel: "color14 color8"
PmenuSbar: ""
PmenuThumb: ""
Question: ""
Search: "background color3"
SpecialKey: ""
SpellBad: "color7 - u"
SpellLocal: "@SpellBad"
SpellCap: "@SpellBad"
SpellRare: "@SpellBad"
StatusLine: "foreground color0"
StatusLineNC: "foreground color8"
TabLine: "color7 color0"
TabLineFill: "- color0"
TabLineSel: "foreground color4"
Title: "color14"
Visual: "- visualSelection"
VisualNOS: ""
WarningMsg: ""
WildMenu: "foreground color8"
# BASE SYNTAX
Comment: "color7"
Constant: "color3"
String: "color10" # Constant
Character: "" # Constant
Boolean: "color9" # Constant
Number: "@Boolean" # Constant
Float: "@Boolean" # Constant
Identifier: "color3"
Function: "color12" # Identifier
Statement: "color4"
Conditional: "@Keyword" # Statement
Repeat: "@Keyword" # Statement
Label: "@Keyword" # Statement
Operator: "@Constant" # Statement
Keyword: "color4" # Statement
Exception: "color1" # Statement
PreProc: "@Constant"
Include: "color6" # PreProc
Define: "@Include" # PreProc
Macro: "@Include" # PreProc
PreCondit: "" # PreProc
Type: "color9"
StorageClass: "@Keyword" # Type
Structure: "color4" # Type
Typedef: "color4" # Type
Special: "@Keyword"
SpecialChar: "" # Special
Tag: "color4" # Special
Delimiter: "" # Special
SpecialComment: "color14" # Special
Debug: "color13" # Special
Underlined: "color15 - u"
Ignore: "@Comment"
Error: "color1"
Todo: "color13"
# tpope/vim-fugitive
diffAdded: "@DiffAdd"
diffRemoved: "@DiffDelete"
