# Apply this configuration to two keyboards (if connected)
- keyboards: [ "Lenovo TrackPoint Keyboard II", "AT Translated Set 2 keyboard", "OBINS OBINS\nAnnePro2"]

  keymap:
    capslock: 'fn_1'
    #leftalt: leftctrl
    #sysrq: rightmeta
  # Specify layered configurations (much similar to fn+F keys)
  layers:
    # Specify the modifiers of the layer
    #- modifiers: ['fn_1']
    - modifiers: ['capslock']
      keymap:
        h: left
        j: down
        k: up
        l: right
        u: pageup
        o: pagedown
        p: home
        1: f1
        2: f2
        3: f3
        4: f4
        5: f5
        6: f6
        7: f7
        8: f8
        9: f9
        0: f10
        minus: f11
        equal: f12
        semicolon: end
